# CREATE QUESTION
POST http://localhost:3000/question
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "title": "Post Question",
    "body": "Post Body"
}

###

# GET ALL QUESTIONS
GET http://localhost:3000/question

###

# GET USER QUESTIONS
GET http://localhost:3000/question/user/c3f3d19c-53fe-4968-b00c-11434d21c71c

###

# GET QUESTION BY ID
GET http://localhost:3000/question/50bfc16f-29ce-470a-9e0a-307431480703

###

# UPDATE QUESTION BY ID
PUT http://localhost:3000/question/50bfc16f-29ce-470a-9e0a-307431480703
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "title": "Put Question",
    "body": "Put Body"
}

###

# DELETE QUESTION BY ID
DELETE http://localhost:3000/question/50bfc16f-29ce-470a-9e0a-307431480703
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
