# CREATE ANSWER
POST http://localhost:3000/answer/question/50bfc16f-29ce-470a-9e0a-307431480703
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "body": "Post Answer"
}

###

# GET ALL ANSWERS (WITH PAGINATION)
GET http://localhost:3000/answer?page=1&pageSize=10

###

# GET ALL ANSWERS (WITH SEARCH)
GET http://localhost:3000/answer?search=put

###

# GET QUESTION ANSWERS
GET http://localhost:3000/answer/question/50bfc16f-29ce-470a-9e0a-307431480703

###

# GET USER ANSWERS
GET http://localhost:3000/answer/user/c3f3d19c-53fe-4968-b00c-11434d21c71c

###

# GET ANSWER BY ID
GET http://localhost:3000/answer/d76c9a94-2772-4dcf-a850-c4e13e1acf1c

###

# UPDATE ANSWER BY ID
PUT http://localhost:3000/answer/d76c9a94-2772-4dcf-a850-c4e13e1acf1c
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "body": "Put Answer"
}

###

# DELETE ANSWER BY ID
DELETE http://localhost:3000/answer/d76c9a94-2772-4dcf-a850-c4e13e1acf1c
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
