GET http://localhost:3000/user
Authorization: Bearer {{$dotenv AUTH_TOKEN}}

###

GET http://localhost:3000/user/57d964c5-e358-48d8-93a2-098d8d410f05
Authorization: Bearer {{$dotenv AUTH_TOKEN}}

###

POST http://localhost:3000/user/signup
Content-Type: application/json

{
  "name": "Test Post",
  "email": "test@post.com",
  "password": "@Post1234"
}

###

PUT http://localhost:3000/user/57d964c5-e358-48d8-93a2-098d8d410f05
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
  "name": "Test Put",
  "email": "test@put.com"
}

###

PATCH http://localhost:3000/user/password/57d964c5-e358-48d8-93a2-098d8d410f05
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
  "password": "@Patch1234"
}

###

DELETE http://localhost:3000/user/57d964c5-e358-48d8-93a2-098d8d410f05
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
