GET http://localhost:3000/user

###

GET http://localhost:3000/user/57d964c5-e358-48d8-93a2-098d8d410f05

###

POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "Test Post",
  "email": "test2@post.com",
  "password": "@Post1234"
}

###

PUT http://localhost:3000/user/57d964c5-e358-48d8-93a2-098d8d410f05
Content-Type: application/json

{
  "name": "Test Put",
  "email": "test@put.com"
}

###

PATCH http://localhost:3000/user/57d964c5-e358-48d8-93a2-098d8d410f05/password
Content-Type: application/json

{
  "password": "@Patch1234"
}

###

DELETE http://localhost:3000/user/57d964c5-e358-48d8-93a2-098d8d410f05
