# CREATE USER
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "User Test",
    "email": "user@test.com",
    "password": "@Test123",
    "passwordConfirmation": "@Test123"
}

###

# GET ALL USERS (WITH PAGINATION)
GET http://localhost:3000/user?page=1&pageSize=10

###

# GET ALL USERS (WITH SEARCH)
GET http://localhost:3000/user?search=put

###

# GET USER BY ID
GET http://localhost:3000/user/c3f3d19c-53fe-4968-b00c-11434d21c71c

###

# UPDATE USER BY ID
PUT http://localhost:3000/user/c3f3d19c-53fe-4968-b00c-11434d21c71c
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "name": "Test Put",
    "email": "test@put.com"
}

###

# UPDATE USER PASSWORD BY ID
PATCH http://localhost:3000/user/561ecd94-72e7-412d-82ee-c87873391c64/password
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "currentPassword": "@Test123",
    "password": "@Test1234",
    "passwordConfirmation": "@Test1234"
}

###

# DELETE USER BY ID
DELETE http://localhost:3000/user/c3f3d19c-53fe-4968-b00c-11434d21c71c
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
